### ISSUE TITLE
on manga verde beach 12 appartment, I had put sleeping capacity “6” in the admin panel, but it shows max 4 in the dropdown menu

### ISSUE THREAD

**Issue by grubobeats** [grubobeats/manga-verde-beach#10]
on manga verde beach 12 appartment, I had put sleeping capacity “6” in the admin panel, but it shows max 4 in the dropdown menu

**Comment by grubobeats** [comment]
It is not connected with it. Connecting is too difficult. I added 6 manually.

**Comment by anthonyasael** [comment]
Ok all appartements are 6 people max,  except one apartment which is 4 People max (apt number 7). Can you change that manually as well.?

**Comment by grubobeats** [comment]
I can't. But If they will choose that one they will receive an error that they can book only up to 4 people.

**Comment by anthonyasael** [comment]
Ok
