### ISSUE TITLE
on manga verde beach 12 appartment, I had put extra price of 8 euros per additional person that would stay. It doesn’t seem to work

### ISSUE THREAD

**Issue by grubobeats** [grubobeats/manga-verde-beach#11]
on manga verde beach 12 appartment, I had put extra price of 8 euros per additional person that would stay. It doesn’t seem to work

**Comment by grubobeats** [comment]
It works, just you need to understand how:
Here you are entering price for 1 person.
<img width="1434" alt="screen shot 2016-09-16 at 11 38 04" src="https://cloud.githubusercontent.com/assets/14358225/18580074/1692c1a2-7c02-11e6-9480-3fe87069c499.png">

And here you are adding how much you want to add for two 2 people, 3 people, 4 and so on:

<img width="906" alt="screen shot 2016-09-16 at 11 39 21" src="https://cloud.githubusercontent.com/assets/14358225/18580107/3f722bf8-7c02-11e6-853a-95c683ac708a.png">

**Comment by anthonyasael** [comment]
Ok got it now ☺

**Comment by anthonyasael** [comment]
I tried and couldnt make it work. Can you please check what am i doing wrong ?
i have the base price for 2 people then adding 8 euros for each extra person....

**Comment by anthonyasael** [comment]
can you please help here ?

**Comment by grubobeats** [comment]
Ok, not a problem, just send me name of apartment and I will do it, so you can see how it is done and make it yourself in future.

**Comment by anthonyasael** [comment]
any of them. they have all the same rule ;-)

by the way, i have just created apt 10, but it doesnt show up on the website. not sure why....

**Comment by grubobeats** [comment]
I made it to work for "Manga Verde Beach 9: Sky and Ocean View" you can look in to the settings about it and see how it was done. Anyway, tomorrow in my spare time I will write on Wiki about it.

**Comment by anthonyasael** [comment]
ok great i will look into it.
Tonight i will  send oyu more questions for the wiki.

could you see for number 10 ?
i think i found the problem. It got updated on http://rental.givemejobtoday.com/apartments/ but not on http://rental.mangaverdebeach.com/apartments/ !!!

**Comment by anthonyasael** [comment]
same that i changed some settings on the fb feed. it changed it on http://rental.givemejobtoday.com/news but not on http://rental.mangaverdebeach.com/news....

**Comment by anthonyasael** [comment]
Could you write the wiki about it?

**Comment by anthonyasael** [comment]
please dont forget

**Comment by grubobeats** [comment]
Of course, you shouldn't make changes anymore to http://rental.givemejobtoday.com. Since we moved to http://rental.mangaverdebeach.com you are editing and making changes to http://rental.mangaverdebeach.com/wp-admin

**Comment by anthonyasael** [comment]
yes got that now ;-). but i was meaning the wiki about the pricing ;-)

**Comment by grubobeats** [comment]
Ok, I will write about it, don't worry. Anyway, anytime later if you stock with something you can contact me and I will help. So don't be worried if we miss something in the guide now. I am not going to write an essay about this. :)

**Comment by anthonyasael** [comment]
ok, thx ;=-)
