### ISSUE TITLE
can you erase the url http://rental.givemejobtoday.com/photos/#itamarca that was with a typo.

### ISSUE THREAD

**Issue by grubobeats** [grubobeats/manga-verde-beach#12]
can you erase the url http://rental.givemejobtoday.com/photos/#itamarca that was with a typo.

**Comment by grubobeats** [comment]
I can't find this, please send me some screenshot.

**Comment by grubobeats** [comment]
Still waiting...

**Comment by anthonyasael** [comment]
it has been erased already. maybe when you erased all drafts.
