### ISSUE TITLE
if only one night is booked, can you put as message “minimum 2 nights required for this booking”, instead of “no room available” ?

### ISSUE THREAD

**Issue by grubobeats** [grubobeats/manga-verde-beach#13]
if only one night is booked, can you put as message “minimum 2 nights required for this booking”, instead of “no room available” ?

**Comment by grubobeats** [comment]
I can't do that, but I changed text to this: 
`No room availability or you are trying to book for less than two nights.`

**Comment by anthonyasael** [comment]
Ok, can you please edit it to :
....  Tô book for less than the minimum required nights.

**Comment by grubobeats** [comment]
Added.
