### ISSUE TITLE
when I order through bank transfer, to which email do I receive the order ?

### ISSUE THREAD

**Issue by grubobeats** [grubobeats/manga-verde-beach#16]
when I order through bank transfer, to which email do I receive the order ?

**Comment by grubobeats** [comment]
Right now it goes to my email. I just changed to your email info@MangaVerdeBeach.com.

**Comment by anthonyasael** [comment]
please change it to anthonyasael@gmail.com

**Comment by grubobeats** [comment]
Changed.
