### ISSUE TITLE
at checkout, can you add a compulsory “Accept house rules” that could be clicked and accessed also if necessary.

### ISSUE THREAD

**Issue by grubobeats** [grubobeats/manga-verde-beach#2]
at checkout, can you add a compulsory “Accept house rules” that could be clicked and accessed also if necessary.

**Comment by grubobeats** [comment]
Added:

<img width="1680" alt="screen shot 2016-09-16 at 12 26 34" src="https://cloud.githubusercontent.com/assets/14358225/18581343/d2203714-7c08-11e6-8e5c-0fb16ca916fc.png">

**Comment by anthonyasael** [comment]
Can you make click able the house policies towards our house rules. I think (if possible) that a pop-up would be better

**Comment by grubobeats** [comment]
In this case popup is not a very good option because we already have content on the page (bad for SEO). I added it to open new page with policies.

**Comment by anthonyasael** [comment]
Ok good
