### ISSUE TITLE
please change font of the http://www.mangaverdebeach.com/choose/ , I am still not convinced for the current one  

### ISSUE THREAD

**Issue by grubobeats** [grubobeats/manga-verde-beach#20]
please change font of the http://www.mangaverdebeach.com/choose/ , I am still not convinced for the current one

**Comment by anthonyasael** [comment]
Also the font of the choose page. please send me 3-4 options to choose from, so it will be much easiers instead of going always back and forward....

**Comment by grubobeats** [comment]
Your current website <http://www.mangaverdebeach.com> is made very, very, very wrong way. I don't want to make there more changes than I already did because later I don't want to spend time on reversing things and fixing website.
It looks very decent. If you want me to spend few more days making few prototypes of it for you to choose, sorry but it is not going to happen with this budget.

**Comment by anthonyasael** [comment]
I am just asking about changing the font of on the choose page. I am asking this since over 2 weeks now...
if you dont want to do prototypes, can you just change the current one to something different so that we can finally close this chapter ?

**Comment by anthonyasael** [comment]
i am online also for the 2 next hours, so if you want you can ask me directly when you change it.....

**Comment by grubobeats** [comment]
Please, choose font here <https://fonts.google.com/> and I will add it to the site.
