### ISSUE TITLE
local time

### ISSUE THREAD

**Issue by anthonyasael** [grubobeats/manga-verde-beach#25]
can you put the local time on the home to the correct time (Brazilia Time)

**Comment by grubobeats** [comment]
Done.

**Comment by anthonyasael** [comment]
the temperature have disappeared .... ?

**Comment by grubobeats** [comment]
You said earlier that you want it to disappear.

**Comment by grubobeats** [comment]
I can't do anything today. Leaving all this issues for the morning.

**Comment by anthonyasael** [comment]
ok, hopefully. it will be done tomorrow then.
Also the font of the choose page. please send me 3-4 options to choose from, so it will be much easiers instead of going always back and forward....

**Comment by grubobeats** [comment]
It shows weather now.
