### ISSUE TITLE
slideshow

### ISSUE THREAD

**Issue by anthonyasael** [grubobeats/manga-verde-beach#26]
(see email) 
I have tried to upload an image with double resolution version for the 3rd on the homepage, but I see absolutely no difference in the low res rendering on the website. Look at the original picture in attached and see the difference in the slide show rendering. Can you make look similar resolution on the photo ?
Other point, while copying the image, something went wrong apparently bcause the slideshow is not looping anymore, but I don’t think touching anything else.
Can you please check ?

Kind Regards, 
Anthony

**Comment by grubobeats** [comment]
It is because the image you uploaded is nearly the same size as the image before, only little bit smaller.

Image | Size
------------ | -------------
Old image | 1024x684px
New image | 1024x644px

**Comment by anthonyasael** [comment]
the first image was 200kb and the new one is 500kb. I believe it is the slideshow app which is reducing the resolution of the image to something very low. If you open the image outside the slideshow and compare it with the one inside the slideshow, the resolution is totally different. Looks like the image inside the slideshow is reduced to something lower than 100k....

**Comment by grubobeats** [comment]
I downloaded your image from email, and checked size from there. Yes, size in kb is different, but image resolution is nearly the same.

**Comment by grubobeats** [comment]
Image looks nice when you open it, but image is not big enough.

It looks nice when you open it on computer, but when you stretch it to the size of the full screen you are getting the same result as we have on the site. **Image must be bigger**.
