### ISSUE TITLE
booking form

### ISSUE THREAD

**Issue by anthonyasael** [grubobeats/manga-verde-beach#28]
add email+phone inside the New customer booking automatic emails

**Comment by grubobeats** [comment]
This I don't understand...

**Comment by anthonyasael** [comment]
When someone makes a booking, I receive an automated email from awe. However in that email there is only the physical address and name of the person. There no email nor phone details. Can you add it?

**Comment by anthonyasael** [comment]
See also email I sent on this on 21st sept

**Comment by grubobeats** [comment]
I guess that you are receiving two emails. One from awe and there I can't add more info. And one from website and there you should have all the data that you need. It sends emails to this email: anthonyasael@gmail.com

**Comment by anthonyasael** [comment]
i just receive one email. i have forwarded it to you again. it comes from wordpress@rental.givemejobtoday.com
i am surprised no contact email or phone is included in here. 
i didnt receive any other email

**Comment by anthonyasael** [comment]
could you look into that as well ?
