### ISSUE TITLE
http://rental.givemejobtoday.com/awe-booking-check/

### ISSUE THREAD

**Issue by anthonyasael** [grubobeats/manga-verde-beach#29]
on http://rental.givemejobtoday.com/awe-booking-check/ on the top left corner there is YOU ARE BOOKING ROOM 1. can you eliminate this sentence as it makes no sense to me. 

just above, you have "SELECT ROOMS", can you chance it to "SELECT APARTMENTS ?

![image](https://cloud.githubusercontent.com/assets/22237959/18732703/d3bf204e-803b-11e6-9ab0-413909aeb098.png)

**Comment by grubobeats** [comment]
Changed, but because of cache on Bluehost it will take some time to be seen (1-2 days)

**Comment by anthonyasael** [comment]
ok still not there for the moment. i will let you know when it appears

**Comment by anthonyasael** [comment]
can you double check this please as it is still not working....

**Comment by grubobeats** [comment]
Of, course. I forgot to save... Now it doesn't shows any more.

**Comment by anthonyasael** [comment]
you have also "SELECT ROOMS", can you change it to "SELECT APARTMENTS ?

**Comment by grubobeats** [comment]
Changed.
