### ISSUE TITLE
homepage reservation

### ISSUE THREAD

**Issue by anthonyasael** [grubobeats/manga-verde-beach#30]
small bug on the homepage. you can reserve upto 4 people and not 6 as it should and as it is on the other pages. Can you fix it ?
thx

**Comment by grubobeats** [comment]
Done.

**Comment by anthonyasael** [comment]
content://media/external/file/12830
Look at the screen shot here. When trying to reserve from home page on mobile phone, I cannot go to lower dates because there is a design overlap...

**Comment by grubobeats** [comment]
Fixed.

**Comment by anthonyasael** [comment]
thank you . design overlap is working but you can still reserve upto 4 people only and not 6 as it should and as it is on the other pages. Can you fix it ?

**Comment by grubobeats** [comment]
Fixed.
