### ISSUE TITLE
pricing in the future

### ISSUE THREAD

**Issue by anthonyasael** [grubobeats/manga-verde-beach#31]
Hi, maybe something to add in hte admin guide. I dont see how i can change the pricing for the future. For example, i would like to set pricing for New Years. Usually you can charge at least 50% higher that week and as you can imagine a key element for us. How can you do that ?

**Comment by grubobeats** [comment]
I already gave you there extended documentation about booking. Here it is again <http://awethemes.com/docs/awebooking/#pid-352>

**Comment by anthonyasael** [comment]
Thx. I found it in the meanwhile. But can you please put this link inside the admin guide. It will be easier to find back some months from now

**Comment by anthonyasael** [comment]
also to be added on the admin giude, please.

**Comment by anthonyasael** [comment]
also to be added on the admin giude, please.
