### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by anthonyasael** [grubobeats/manga-verde-beach#32]
making a google search on Manga Verde Beach i arrived on this page
![image](https://cloud.githubusercontent.com/assets/22237959/18851544/ec95c2a0-8412-11e6-9e9a-b882784ac0c0.png)
I guess that is something that need to be fixed for the current SEO, as we dont want our home page to appear as "choose".
thx

**Comment by grubobeats** [comment]
Fixed, but it will take Google few days to reindex it.

**Comment by anthonyasael** [comment]
great, working now !
