### ISSUE TITLE
Português version of the site 

### ISSUE THREAD

**Issue by anthonyasael** [grubobeats/manga-verde-beach#34]
See email with all translation to be put on the .br domain

**Comment by grubobeats** [comment]
Translated. If there will be some issues write about it.
Right now you can't see apartments there because you need to copy apartments to Portuguese version of website.
It is very easy to be done, and [here](https://github.com/grubobeats/manga-verde-beach/wiki/Translating) is explained how to do it.

**Comment by anthonyasael** [comment]
ok will do the apartment part. But please dont forget this need also to be moved on the mangaverdebeach.com.br domain.
