### ISSUE TITLE
home page menu

### ISSUE THREAD

**Issue by anthonyasael** [grubobeats/manga-verde-beach#36]
hi, i guess it is work in progress to add the BR domain. but the menu is scrambled as you can see on my screen (1366x768)
![image](https://cloud.githubusercontent.com/assets/22237959/18940605/212aa6ec-85e0-11e6-8c11-de60362de695.png)

**Comment by anthonyasael** [comment]
![image](https://cloud.githubusercontent.com/assets/22237959/18940613/36d17a98-85e0-11e6-8997-2de8f9166e13.png)

**Comment by grubobeats** [comment]
Fixed.

**Comment by anthonyasael** [comment]
looks nice ;-)
