### ISSUE TITLE
in the future, I might want to change photos of the gallery header on apartments page

### ISSUE THREAD

**Issue by grubobeats** [grubobeats/manga-verde-beach#4]
in the future, I might want to change photos of the gallery header on apartments page. I think all images is in too low resolution for laptop viewing. I tried to look for it how to access it to make the changes but couldn’t find it. (maybe useful to add this in the admin guide)

**Comment by grubobeats** [comment]
If you think about changing this image:
<img width="1680" alt="screen shot 2016-09-16 at 12 12 43" src="https://cloud.githubusercontent.com/assets/14358225/18580928/ec090ea0-7c06-11e6-9f66-aab42ef70d0d.png">
You click on "edit page" on upper panel. It will take you on page for editing page.
Down (nearly at the end) you have "Header options"
<img width="1680" alt="screen shot 2016-09-16 at 12 14 04" src="https://cloud.githubusercontent.com/assets/14358225/18580984/337cccc2-7c07-11e6-9790-c8f3e66b3e0b.png">
It can be image, color or slider(gallery) as here. If it is image or color you are changing it on the same page.
If it is a slider/gallery as it is case here than you are changing it in Slider settings here choose slider:

<img width="1680" alt="screen shot 2016-09-16 at 12 17 34" src="https://cloud.githubusercontent.com/assets/14358225/18581074/92d2034a-7c07-11e6-9cd1-2592cbbdb35c.png">

And here go to slides and play with them.

<img width="1680" alt="screen shot 2016-09-16 at 12 17 15" src="https://cloud.githubusercontent.com/assets/14358225/18581053/849c0190-7c07-11e6-94db-cf891beaf666.png">

**Comment by anthonyasael** [comment]
Ok, I will play once I am back on my computer
