### ISSUE TITLE
I have seen that you added a Sales banner on the superior vila. Is that something you added through the admin panel ?

### ISSUE THREAD

**Issue by grubobeats** [grubobeats/manga-verde-beach#5]
I have seen that you added a Sales banner on the superior vila. Is that something you added through the admin panel ?

**Comment by grubobeats** [comment]
Yes, of course, in apartment edit you can do it, here is where and how:

<img width="1506" alt="screen shot 2016-09-16 at 12 10 02" src="https://cloud.githubusercontent.com/assets/14358225/18580848/8aa44422-7c06-11e6-9bef-915b95327ccd.png">

**Comment by anthonyasael** [comment]
Ok, great. I am sure, I will discover more things in the admin guide
