### ISSUE TITLE
can you add the sea view icon in the apartment description AND also in the short description (you can do it one only, I will do it on others)

### ISSUE THREAD

**Issue by grubobeats** [grubobeats/manga-verde-beach#8]
can you add the sea view icon in the apartment description AND also in the short description (you can do it one only, I will do it on others)

**Comment by grubobeats** [comment]
Added.
<img width="1025" alt="screen shot 2016-09-16 at 12 06 58" src="https://cloud.githubusercontent.com/assets/14358225/18580765/1ec6d0a8-7c06-11e6-8f7f-52dfd96bd234.png">
<img width="1272" alt="screen shot 2016-09-16 at 12 07 11" src="https://cloud.githubusercontent.com/assets/14358225/18580767/1ee7f472-7c06-11e6-9747-bae087ebd2b8.png">

**Comment by anthonyasael** [comment]
Could you add it also on the short description?  I couldn't see it

**Comment by grubobeats** [comment]
It is added. Check on first screenshot here.

**Comment by anthonyasael** [comment]
Ok seen it now. Sorry my fault
