### ISSUE TITLE
 would it be possible to use the BRL currency as main currency for the site in Portuguese. Does it require much efforts to do that?

### ISSUE THREAD

**Issue by grubobeats** [grubobeats/manga-verde-beach#9]
would it be possible to use the BRL currency as main currency for the site in Portuguese. Does it require much efforts to do that?

**Comment by grubobeats** [comment]
No, because we are having only one website and we are putting main currency based on website, not based on language of website.

**Comment by anthonyasael** [comment]
Even if we have two different domains?

**Comment by grubobeats** [comment]
Even like that. This is looking for where it is hosted, and it will be hosted on the same folder.

**Comment by anthonyasael** [comment]
Ok. Would it be easy for me to change the main currency in the future if needed it to be. I will start with euros as it is, but may want to change it to BRL in December during the Brazilian high season...

**Comment by grubobeats** [comment]
Very easy, I will write about it [here](https://github.com/grubobeats/manga-verde-beach/wiki)

**Comment by anthonyasael** [comment]
ok great. will it change also the currency on the homepage automatically ?

**Comment by anthonyasael** [comment]
will it ?

**Comment by grubobeats** [comment]
No, for that you will have to contact me to change.

**Comment by anthonyasael** [comment]
ok
